### ISSUE TITLE
New cloud object of interest and associated variables

### ISSUE THREAD

**Issue by swr99ejo** [ACTRIS-Data-Centre/actris-vocabulary#11]
Some measurements of liquid water variables are not always able to distinguish between liquid cloud droplets and larger precipitation drops (rain or drizzle). These would be useful for in situ probes that measure bulk liquid water content and some microwave radiometer measurements (and for some satellite comparison products)

New object of interest: Liquid water
Description: Bulk parameter that includes all hydrometeors in liquid phase, i.e. liquid droplets, drizzle droplets and raindrops, if present

New cloud variables:
liquid water mass concentration:
- OBSERVED PROPERTY: [ mass concentration]
- actris_vocab/liquidwatermassconcentration 
liquid water total column mass content:
- OBSERVED PROPERTY: [column mass content]
- actris_vocab/liquidwatercolumnmasscontent

**Comment by swr99ejo** [comment]
From some instrument perspectives, yes, cloud liquid water chemical composition is not strictly limited to liquid cloud droplets. Satellites and models also often combine all warm phases into one category (all warm liquid), combine all ice phases, and also combine both warm and ice into a **total bulk water**. Some models often combine **graupel** and **hail** categories, however, this is not necessary for us to do..

**Comment by markusfiebig** [comment]
liquid water would include liquid droplet, drizzle droplet, raindrop
hydrometeor would include liquid droplet, drizzle droplet, raindrop, ice particle, graupel, hail
proposal by @swr99ejo and @markusfiebig .

Will have consequences for cloud in situ variables. Need to discuss / reconfirm with CIS which combinations they need as variables.

**Comment by markusfiebig** [comment]
Definition of liquid water not used by CIS variables. Therefore ok with CIS. CIS uses liquid droplet, and [that definition](https://vocabulary.actris.nilu.no/actris_vocab/liquiddroplet) is fine.

CIS points out that definition of hydrometeor should coincide with external definitions, e.g. [AMS](https://glossary.ametsoc.org/wiki/Hydrometeor).

**Comment by markusfiebig** [comment]
Implemented in dev version, will be rolled out with next version.
