### ISSUE TITLE
move ceilometers to new group under lidar

### ISSUE THREAD

**Issue by swr99ejo** [ACTRIS-Data-Centre/actris-vocabulary#12]
New lidar type: automatic lidar ceilometer

Active remote sensing instrument operating at visible or near-infrared wavelengths for detecting the scattering of particles in the atmosphere.

All ceilometer types except Vaisala CL61

New lidar type: automatic lidar ceilometer with depolarisation

Active remote sensing instrument operating at visible or near-infrared wavelengths for detecting the scattering of particles in the atmosphere with the capability of collecting both polarization components of the linearly polarized emitted laser light.

Only Vaisala CL61 (at this stage)

**Comment by markusfiebig** [comment]
Re-confirm whether this also refers to Lufft and Campbell ceilometers.

**Comment by siiptuo** [comment]
Yes. Only "Vaisala CL61" goes to "automatic lidar ceilometer with depolarisation". All other ceilometers, including Lufft and Campbell, go to "automatic lidar ceilometer".

**Comment by markusfiebig** [comment]
Included in next version of vocabulary.
