### ISSUE TITLE
Introduce object categories for those object groups used in DMP Appendix 1

### ISSUE THREAD

**Issue by markusfiebig** [ACTRIS-Data-Centre/actris-vocabulary#15]

**Comment by kjes4pres** [comment]
OVOCs is missing as an object group. Is used as an object group i DMP appendix 1.

**Comment by kjes4pres** [comment]
terpenes is missing as an object group. It is used as an object group in DMP appendix 1.

**Comment by kjes4pres** [comment]
NMHCs is missing as an object group. It is used as an object group in DMP appendix 1. Also missing a list in appendix 1 over the components. This also goes for "condensable vapors", also in DMP appendix 1. Object group and list over them missing.

**Comment by markusfiebig** [comment]
All fixed, except for condensable vapours. For those, we need to request a list from the responsible TC.

**Comment by markusfiebig** [comment]
Part of next release, missing organic tracers moved to new issue.
