### ISSUE TITLE
"Inductively coupled plasma mass spectrometer" wrong placing

### ISSUE THREAD

**Issue by kjes4pres** [ACTRIS-Data-Centre/actris-vocabulary#16]
instrument->instrument type->LIDAR->inductively coupled plasma mass spectrometry, inductively coupled plasma–atomic emission spectrometry , inductively coupled plasma–optical emission spectrometry 

The last three doesnt belong under lidar, and must be rmeoved. They are placed correclty under "
inductively coupled plasma spectrometer"

**Comment by markusfiebig** [comment]
fixed in dev version

**Comment by markusfiebig** [comment]
Part of next release
