### ISSUE TITLE
Missing vocabulary for Aerosol remote sensing from Annex I in DMP

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-vocabulary#17]
From Annex I in the ACTRIS DMP, there is missing vocabulary for "Particle layer geometrical properties (height and thickness)" under Aerosol remote sensing. Should be discussed in ET.

**Comment by lisemurberg** [comment]
"Spectral Downward Sky Radiances" missing in vocabulary.

**Comment by markusfiebig** [comment]
Implemented in dev version. _downwelling spectral radiance_ was implemented as _downward   spectral radiance_.
