### ISSUE TITLE
"nano aerosol particle number concentration" missing

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-vocabulary#18]
From Annex I 'Nanoparticle number concentration' missing for Aerosol In-Situ. Suggestion to name it: nano aerosol particle number concentration, and let it be under aerosol particle number concentration.

**Comment by markusfiebig** [comment]
Has been added to dev version.

**Comment by markusfiebig** [comment]
Part of next release
