### ISSUE TITLE
Automatic low-power lidar and ceilometer (ALC) instrument types

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/actris-vocabulary#2]
Currently the vocabulary is missing all ceilometers. At least the following instruments are recommended by CCRES:

- Vaisala CL31
- Vaisala CL51
- Vaisala CL61
- Lufft CHM 15k 
- Lufft CHM 15k-x

**Comment by markusfiebig** [comment]
Expert team accepts!

**Comment by tukiains** [comment]
These ceilometers could be also added:

- Lufft CHM 8k
- Campbell Scientific CS135
- Campbell Scientific SkyVUEPRO

**Comment by markusfiebig** [comment]
Transferred to master table.
