### ISSUE TITLE
relative and specific humidity missing

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-vocabulary#20]
Include both relative and specific humidity in vocabulary. 

In vocabulary for 'atmospheric state' https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/page/airhumidity -> specific humidity. 
For instruments (new matrix) -> relative humidity

**Comment by siiptuo** [comment]
We have both **specific** and **relative** humidity in Cloudnet products. These are well-defined quantities also found in CF conventions as `specific_humidity` and `relative_humidity`.

As a related issue, we also need definition for **absolute** humidity. This seems to be `mass_concentration_of_water_vapor_in_air` in CF conventions. What do you think?

**Comment by swr99ejo** [comment]
I would prefer **specific**, **relative** and **absolute** humidity as these have well defined meanings. Humidity alone is open to interpretation

**Comment by markusfiebig** [comment]
draft:
water vapour mass concentration, alt label : absolute humidity
water vapour mass fraction, alt label: specific humidity
water vapour liquid water saturation fraction, alt label: relative humidity with respect to water
water vapour ice water saturation fraction, alt label: relative humidity with respect to ice

to be reconfirmed by @swr99ejo and @markusfiebig

**Comment by markusfiebig** [comment]
Has been reconfirmed!

**Comment by markusfiebig** [comment]
Has been implemented in dev, rolled out in next version.
