### ISSUE TITLE
instrument types, add definitions where lacking

### ISSUE THREAD

**Issue by kjes4pres** [ACTRIS-Data-Centre/actris-vocabulary#23]
Instrument types, some are missing definitions. ex. "photometer". But also components on lower level are missing definitions, ex. 
inductively coupled plasma spectrometer -> inductively coupled plasma–atomic emission spectrometry .  Need to look through instrument types, and add definitions where they are missing.

**Comment by markusfiebig** [comment]
Completed, with only one exception (_inductively coupled plasma–optical emission spectrometry_). Responsible TC has been contacted.
