### ISSUE TITLE
HALO Photonics Doppler lidars

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/actris-vocabulary#26]
Following instruments should be added in "Doppler lidar" category:

| Name | Description |
| - | - |
| HALO Photonics StreamLine | Doppler lidar with range up to ~10 km |
| HALO Photonics StreamLine XR | Doppler lidar with range up to ~12 km |
| HALO Photonics StreamLine XR+ | Doppler lidar with range up to ~15 km |
| HALO Photonics StreamLine Pro | Doppler lidar with no external moving parts with range up to ~10 km |

**Comment by markusfiebig** [comment]
Added to next version of vocabulary
