### ISSUE TITLE
Controlled list: Licenses

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-vocabulary#30]
After discussions with GRES on landing pages: 

There should be a controlled list of licenses where these licenses link to creative commons (feks: https://creativecommons.org/licenses/by/4.0/). This is so that the license field on the landing pages can be linked to this list and that we do not have to update all landing pages if creative commons changes their url.

**Comment by lisemurberg** [comment]
@markusfiebig I see its added in the main vocabulary https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/page/CC-BY-4.0 

Could you add the link to the license (i.e. https://creativecommons.org/licenses/by/4.0/) in the vocabulary? 

And if so, then we can close this issue.

**Comment by markusfiebig** [comment]
Links to the SPDX pages of the licences are already included
