### ISSUE TITLE
Scanning configurations for RPG cloud radars

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/actris-vocabulary#31]
[RPG-FMCW-94S](https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94S) should be deprecated and replaced with:

| term | description |
| - | - |
| RPG-FMCW-94-SP-S | RPG-FMCW 94 GHz single polarization scanning |
| RPG-FMCW-94-DP-S | RPG-FMCW 94 GHz dual polarization scanning |

[RPG-FMCW-35S](https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-35S) should be deprecated and replaced with:

| term | description |
| - | - |
| RPG-FMCW-35-SP-S | RPG-FMCW 35 GHz single polarization scanning |
| RPG-FMCW-35-DP-S | RPG-FMCW 35 GHz dual polarization scanning |

**Comment by markusfiebig** [comment]
Can be implemented!

**Comment by markusfiebig** [comment]
Has been transferred to upcoming version.
