### ISSUE TITLE
ASC vocabulary/landing pages: Extra facility information

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-vocabulary#34]
ASC Vocabulary/landing pages: 
For facilities (i.e. simulation chambers) the landing pages will include:
- Volume 
- Wall material 
- Light source 

Should this be part of the vocabulary or would it be ok to just have it as controlled list? To be discussed

**Comment by gbrissebrat** [comment]
I am not sure to understand why we need that in the vocabulary. 
What do you want to add to the vocabulary? The field name? Or its values? 

I suppose we can provide a definition for these 3 concepts but is it really necessary ? These names are self explanatory. All informations from all landing page will have a definition in the vocabulary? 

If we are considering the possible values. I think Wall materials and light sources could be in a controlled vocabulary, if it's useful?

**Comment by gbrissebrat** [comment]
Current values in Eurochamp:

Light sources:
- Dark chamber
- Fluorescent lamps
- Natural sunlight
- Other artificial light source
- Xenon arc lamps

Wall Types:
- Aluminium
- FEP film
- Pyrex
- Quartz
- Stainless steel

Sources:
https://eurochamp.ipsl.upmc.fr/datacenter-rest/light-sources?sort=name&size=50
https://eurochamp.ipsl.upmc.fr/datacenter-rest/wall-types?sort=name&size=50

**Comment by lisemurberg** [comment]
From meeting 1. Dec 2023 on ASC vocabulary:

Include "Chamber light sources" and "Chamber wall types" as controlled lists (not in main vocabulary). 
FET film can include a description Fluorinated Ethylene Propylene (or teflon).

**Comment by markusfiebig** [comment]
Accepted by ET, will be included in next version of controlled lists.

**Comment by markusfiebig** [comment]
Deployed!
