### ISSUE TITLE
Deprecated items

### ISSUE THREAD

**Issue by tukiains** [ACTRIS-Data-Centre/actris-vocabulary#36]
When updating the vocabulary, it would be good to maintain deprecated terms in the production version and link them to their new, updated definitions. This approach ensures continuity and clarity, especially for users who might access the vocabulary through older references.

For example, the URL https://vocabulary.actris.nilu.no/actris_vocab/METEKMIRA35 was updated to https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/page/MetekMIRA35. While the update is valid, the original link now leads to a 404 error page. Such broken links create confusion as vocabulary URLs are expected to be persistent.

A better strategy would be to mark the original term as deprecated and provide a direct link to the new definition. This method is exemplified in the handling of terms in the Finto vocabulary (see https://finto.fi/yso/en/page/p24381 for reference), where deprecated terms are kept accessible and linked to their updated versions. This approach not only aids in seamless navigation but also preserves the historical context of the vocabulary changes.

**Comment by markusfiebig** [comment]
Has been implemented using this documentation:
https://github.com/NatLibFi/Skosmos/wiki/Data-Model#deprecated-concepts
