### ISSUE TITLE
deposition chemistry vocabulary

### ISSUE THREAD

**Issue by markusfiebig** [ACTRIS-Data-Centre/actris-vocabulary#40]
We are in the process of defining vocabulary for variables describing deposition chemistry (needed to make EBAS content visible).

@swr99ejo , would, in your head, _precipitation mass flux_ a.k.a. _wet deposition_ , be the same as _hydrometeor mass flux_ ? If so, why do we use _hydrometeor_ instead of _precipitation_ ?

This is related to issue #11 .

**Comment by swr99ejo** [comment]
Hydrometeor includes liquid cloud, ice particles, drizzle, rain, so not all particles are precipitating. However, vertical (and horizontal) air motion means that there can be a significant hydrometeor flux without any precipitation present. Note that these mass fluxes are not necessarily with respect to the surface, for surface fluxes we would include a surface_ (sfc_) prefix to the variable names.

**Comment by swr99ejo** [comment]
Only precipitation at the surface, not in the atmosphere. In principle, hydrometeor downward flux at the surface could include situations such as dew or frost, which is not from precipitation..

**Comment by markusfiebig** [comment]
Should we then have "precipitation" as separate matrix, with the definition:

hydrometeor downward flux at the surface, including dew, frost, and fog

?

**Comment by swr99ejo** [comment]
Precipitation implies droplets/drops with appreciable terminal fall velocity, whereas there can be a flux of any droplets/particles due to air motion. Precipitation at the surface is therefore not quite the same as precipitation in the atmosphere

**Comment by markusfiebig** [comment]
Solved!
