### ISSUE TITLE
Instrument types incorrectly listed as instrument models

### ISSUE THREAD

**Issue by siiptuo** [ACTRIS-Data-Centre/actris-vocabulary#43]
The following should not be listed under "instrument model":

- https://vocabulary.actris.nilu.no/actris_vocab/lidarceilometer
- https://vocabulary.actris.nilu.no/actris_vocab/depolarisationlidarceilometer
- https://vocabulary.actris.nilu.no/actris_vocab/Dopplerlidar

The same probably applies to these:

- https://vocabulary.actris.nilu.no/actris_vocab/energydispersiveX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/totalreflectionX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/synchrotronradiationX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/wavelengthdispersiveX-rayfluorescencespectrometer

**Comment by markusfiebig** [comment]
Correctly pointed out, will be corrected.

**Comment by markusfiebig** [comment]
Partly corrected, as far as possible. These items:


- https://vocabulary.actris.nilu.no/actris_vocab/energydispersiveX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/totalreflectionX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/synchrotronradiationX-rayfluorescencespectrometer
- https://vocabulary.actris.nilu.no/actris_vocab/wavelengthdispersiveX-rayfluorescencespectrometer

are at the lowest hierarchy level, and therefore need to included as _instrument model_.
