### ISSUE TITLE
New Doppler lidar instruments to include

### ISSUE THREAD

**Issue by swr99ejo** [ACTRIS-Data-Centre/actris-vocabulary#48]
These instruments should be added to the "Doppler lidar" category:

Name | Description
-- | --
Vaisala WindCube 100S | Doppler lidar with range up to ~15 km
Vaisala WindCube 200S | Doppler lidar with range up to ~15 km
Vaisala WindCube 400S | Doppler lidar with range up to ~19 km
Vaisala WindCube WLS70 | Doppler lidar with 4-beam DBS and range up to ~2 km

Note that these used to be manufactured by Leosphere.

**Comment by markusfiebig** [comment]
Included!
