### ISSUE TITLE
Consistent definitions of "cloud" and "cloud phase"

### ISSUE THREAD

**Issue by markusfiebig** [ACTRIS-Data-Centre/actris-vocabulary#51]
Today, the definition of _cloud phase_ reads:
> Comprised of liquid or solid particles forming clouds, i.e. particles that have passed the thermodynamical threshold for cloud activation. Does not include the gas carrying the cloud particles.

whereas the definition of _cloud_ reads:
> Liquid droplets or ice particles present in sufficient numbers to be detected by lidar or radar. Drizzle-only or rain-only portions of the atmospheric column are not included

The issues are that both definitions refer to the same object, but aren't consistent. In addition the _cloud_ definition refers to specific observation methods, whereas the object intended to be observed exists independent of an observation, and should be defined as such. The observed variable isn't the place to specify measurement artifacts. Since the _cloud phase_ definition is independent of any observation methods, the _cloud_ definition should be changed to:

_Totality of liquid or solid particles forming clouds in a volume, i.e. particles that have passed the thermodynamical threshold for cloud activation. Does not include the gas carrying the cloud particles._

**Comment by swr99ejo** [comment]
Still need to include the rain/drizzle exclusion, so suggest:

_Totality of liquid or solid particles forming clouds in a volume, i.e. particles that have passed the thermodynamical threshold for cloud activation. Does not include the gas carrying the cloud particles. Excludes drizzle-only or rain-only portions of the atmospheric column._

**Comment by markusfiebig** [comment]
Would this work?

_Totality of liquid or solid particles forming clouds in a volume, i.e. particles that have passed the thermodynamical threshold for cloud activation. Does not include the gas carrying the cloud particles. Excludes drizzle-only or rain-only portions in the volume._

**Comment by swr99ejo** [comment]
This might be simpler..

_Totality of liquid or solid particles forming clouds in a volume, i.e. particles that have passed the thermodynamical threshold for cloud activation. Does not include the gas carrying the cloud particles. Excludes volumes that are drizzle-only or rain-only._

**Comment by markusfiebig** [comment]
Ok.

**Comment by markusfiebig** [comment]
Included in dev version
