### ISSUE TITLE
CIS instrument types to add

### ISSUE THREAD

**Issue by rfoesig** [ACTRIS-Data-Centre/actris-vocabulary#56]
PINE:
ice nucleating particle counter (definition below)
Bilfinger Nuclear and Energy Transition GmbH
PINE-05

HINC-Auto:
ice nucleating particle counter (definition below)
ETH Zurich, https://ror.org/05a28rw58
HINC-Auto model 1

definition ice nucleating particle counter:
Instrument designed for measuring the number concentration of particles in an aerosol sample that may act as ice nuclei for liquid cloud droplets by exposing the particles to an atmosphere with a defined water vapour supersaturation and temperature similar to those occuring in clouds.

INSEKT:
droplet freezing array
Karlsruhe Institute of Technology, https://ror.org/04t3en479

PVM:
cloud light scattering photometer
Gerber Scientific, Inc.

Not yet discussed with new unit CCPar:
cloud light scattering spectrometer
Palas GmbH

ion chromatograph offline:
ion chromatograph (Ion chromatograph that is deployed in a lab and receives samples, which were collected in the field and transported to a lab.)

cloud water collector:
cloud water collector (Device for collecting liquid droplets by inertial impaction)

total organic carbon analyzer:
total organic carbon analyzer (Device for the determination of the organic carbon concentration in a sample. This instrument converts the organic carbon in a sample to carbon dioxide (CO2) by either catalytic combustion or wet chemical oxidation. The CO2 formed is then either measured directly by an infrared detector or converted to methane (CH4) and measured by a flame ionization detector.)

The model names for the narrower concepts still need to be defined in some cases.

**Comment by rfoesig** [comment]
We would like to discuss this in our next CIS-DC meeting with you on 28 August 2024, but I think the changes are somehow minor and we can go through quickly. As soon as the names are found, we will provide definitions.

**Comment by markusfiebig** [comment]
Included in current version.
